In [6]:
import numpy as np
import pandas as pd
import sys

path="../PAMAP2_Dataset/Protocol/subject101.dat"

df=pd.read_table(path,sep="\s+",header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
0,8.38,0,104.0,30.0,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,0.008300,0.009250,-0.017580,-61.1888,-38.9599,-58.1438,1.0,0.0,0.0,0.0
1,8.39,0,NaN,30.0,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.006577,-0.004638,0.000368,-59.8479,-38.8919,-58.5253,1.0,0.0,0.0,0.0
2,8.40,0,NaN,30.0,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,0.003014,0.000148,0.022495,-60.7361,-39.4138,-58.3999,1.0,0.0,0.0,0.0
3,8.41,0,NaN,30.0,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,0.003175,-0.020301,0.011275,-60.4091,-38.7635,-58.3956,1.0,0.0,0.0,0.0
4,8.42,0,NaN,30.0,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,0.012698,-0.014303,-0.002823,-61.5199,-39.3879,-58.2694,1.0,0.0,0.0,0.0

In [8]:
sys.path.append("../models/model_based_files/")

In [14]:
df=df[df[1]==4]
df_IMU=df[[i for i in range(20,37)]]

In [15]:
df_IMU.head()

,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36
223759,37.1875,0.197678,9.79963,-1.76714,-0.051800,9.65022,-1.44223,-0.016334,-0.033602,-0.016584,-0.885381,-39.3851,31.2728,1.0,0.0,0.0,0.0
223760,37.1875,-0.034740,9.68661,-1.88714,-0.096535,9.72581,-1.45686,-0.022537,-0.044329,0.020406,-0.421494,-39.6219,31.0343,1.0,0.0,0.0,0.0
223761,37.1875,-0.033397,9.76217,-1.84864,-0.111582,9.71072,-1.44170,-0.018780,-0.079511,0.017635,-0.549476,-39.1684,30.7878,1.0,0.0,0.0,0.0
223762,37.1875,-0.070766,9.61194,-1.81011,-0.066734,9.69557,-1.47224,0.010051,-0.009645,-0.056478,-0.074427,-39.7419,30.6717,1.0,0.0,0.0,0.0
223763,37.1875,-0.069324,9.72516,-1.77173,-0.096637,9.69560,-1.44183,-0.032823,-0.008295,-0.048021,-0.564613,-38.7198,30.6656,1.0,0.0,0.0,0.0

In [16]:
df_1=df_IMU[[21,22,23,27,28,29,30,31,32]]

ImportError: cannot import name 'SpeedRec_1' from 'model_1' (/home/prestige/Documents/GitHub/Speed_Estimation/Processing/../models/model_based_files/model_1.py)